version: '2'
services:
  beta-mediasoup-media-server:
    build: ./
    expose:
      - "3444"
    ports:
      - "3444:3444"
    working_dir: /usr/src/app
    network_mode: host
    shm_size: '1gb'
    environment:
      - numWorkers=1
      - maxBitrate=250000
      - stage=beta
      - serverPort=3444

version: '2'
services:
  production-mediasoup-media-server:
    build: ./
    expose:
      - "3443"
    ports:
      - "3443:3443"
    working_dir: /usr/src/app
    network_mode: host
    shm_size: '1gb'
    environment:
      - numWorkers=1
      - maxBitrate=250000
      - stage=production
      - serverPort=3443
